"use client";

import Image from "next/image";
import { useLayoutEffect, useRef, useState } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

import Container from "@/src/components/ui/Container";
import SectionHeading from "../../ui/SectionHeading";
import { FaCircleCheck } from "react-icons/fa6";

gsap.registerPlugin(ScrollTrigger);

interface TNEAStep {
  number: string;
  navTitle: string;
  title: string;
  description: string;
  points: string[];
  image: string;
}

const steps: TNEAStep[] = [
  {
    number: "01",
    navTitle: "Registration",
    title: "Online Registration",
    description:
      "Begin your TNEA application by visiting the official TNEA portal and creating your account.",
    points: [
      "Visit the official TNEA portal.",
      "Create an account using your email ID or mobile number.",
      "Generate a password.",
      "Log in to continue the application.",
    ],
    image: "/images/admissions/tnea/01-registration.webp",
  },
  {
    number: "02",
    navTitle: "Application Form",
    title: "Fill the Application Form",
    description:
      "Complete the application form with your personal, academic and other required details.",
    points: [
      "Enter personal details.",
      "Provide parent or guardian details.",
      "Enter address and community/category information.",
      "Enter Class 12 academic and school details.",
      "Provide nativity details, if applicable.",
    ],
    image: "/images/admissions/tnea/02-application-form.webp",
  },
  {
    number: "03",
    navTitle: "Documents",
    title: "Upload Documents",
    description:
      "Upload the required certificates and supporting documents as specified by TNEA.",
    points: [
      "Class 10 mark sheet.",
      "Class 12 mark sheet.",
      "Transfer Certificate.",
      "Community Certificate.",
      "Nativity Certificate.",
      "First Graduate Certificate.",
      "Special reservation certificates, if applicable.",
      "Passport-size photograph and signature.",
      "Aadhaar card is recommended.",
    ],
    image: "/images/admissions/tnea/03-documents.webp",
  },
  {
    number: "04",
    navTitle: "Fee Payment",
    title: "Pay the Application Fee",
    description:
      "Complete the application by paying the applicable TNEA registration fee through the available online payment methods.",
    points: [
      "Debit card.",
      "Credit card.",
      "UPI.",
      "Net banking.",
      "Application fee varies by category.",
    ],
    image: "/images/admissions/tnea/04-fee-payment.webp",
  },
  {
    number: "05",
    navTitle: "Verification",
    title: "Certificate Verification",
    description:
      "Your certificates and application details are verified through the applicable TNEA verification process.",
    points: [
      "Verification may be conducted online or through TNEA Facilitation Centres.",
      "Check the submitted information carefully.",
      "Correct any discrepancies within the specified time.",
    ],
    image: "/images/admissions/tnea/05-verification.webp",
  },
  {
    number: "06",
    navTitle: "Random Number",
    title: "Random Number Generation",
    description:
      "A random number is generated as part of the TNEA process and may be used as a tie-breaker when candidates have identical merit.",
    points: [
      "Random number is generated by TNEA.",
      "It can be used as one of the tie-breaking criteria.",
      "Candidates should keep track of the official TNEA updates.",
    ],
    image: "/images/admissions/tnea/06-random-number.webp",
  },
  {
    number: "07",
    navTitle: "Rank List",
    title: "Rank List",
    description:
      "The TNEA rank list is prepared using normalized Class 12 marks in Mathematics, Physics and Chemistry.",
    points: [
      "Mathematics contributes a maximum of 100 marks.",
      "Physics contributes a maximum of 50 marks.",
      "Chemistry contributes a maximum of 50 marks.",
      "Engineering cutoff is calculated out of 200.",
      "Candidates receive their rank based on the applicable TNEA process.",
    ],
    image: "/images/admissions/tnea/07-rank-list.webp",
  },
  {
    number: "08",
    navTitle: "Counselling",
    title: "TNEA Counselling",
    description:
      "Eligible candidates participate in counselling by selecting and locking their preferred college and course choices.",
    points: [
      "Pay the counselling fee.",
      "Select preferred college and course choices.",
      "Arrange choices according to preference.",
      "Lock the selected choices.",
      "Seat allotment is based on rank, category and availability.",
      "Download the provisional allotment.",
    ],
    image: "/images/admissions/tnea/08-counselling.webp",
  },
  {
    number: "09",
    navTitle: "College Reporting",
    title: "Report to the College",
    description:
      "After receiving the allotment, complete the admission process by reporting to the allotted college within the specified deadline.",
    points: [
      "Download the allotment order.",
      "Report to the allotted college within the deadline.",
      "Submit the required original documents.",
      "Complete the admission formalities.",
    ],
    image: "/images/admissions/tnea/09-college-reporting.webp",
  },
];

export default function TNEAApplication() {
  const sectionRef = useRef<HTMLElement>(null);
  const headingRef = useRef<HTMLHeadingElement>(null);
  const introRef = useRef<HTMLParagraphElement>(null);
  const navRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const imageRef = useRef<HTMLDivElement>(null);

  const [activeIndex, setActiveIndex] = useState(0);

  const activeStep = steps[activeIndex];

  useLayoutEffect(() => {
    const section = sectionRef.current;

    if (!section) return;

    const context = gsap.context(() => {
      const heading = headingRef.current;
      const intro = introRef.current;
      const nav = navRef.current;
      const image = imageRef.current;

      const navItems = Array.from(
        section.querySelectorAll<HTMLElement>(".tnea-nav-item"),
      );

      const line = section.querySelector<HTMLElement>(".tnea-progress-line");

      const tl = gsap.timeline({
        scrollTrigger: {
          trigger: section,
          start: "top 80%",
          once: true,
        },
      });

      if (heading) {
        gsap.set(heading, {
          opacity: 0,
          y: 35,
        });

        tl.to(
          heading,
          {
            opacity: 1,
            y: 0,
            duration: 0.8,
            ease: "power4.out",
          },
          0,
        );
      }

      if (intro) {
        gsap.set(intro, {
          opacity: 0,
          y: 25,
        });

        tl.to(
          intro,
          {
            opacity: 1,
            y: 0,
            duration: 0.7,
            ease: "power3.out",
          },
          0.15,
        );
      }

      if (nav) {
        gsap.set(nav, {
          opacity: 0,
          x: -25,
        });

        tl.to(
          nav,
          {
            opacity: 1,
            x: 0,
            duration: 0.8,
            ease: "power4.out",
          },
          0.25,
        );
      }

      if (image) {
        gsap.set(image, {
          opacity: 0,
          x: 30,
          scale: 0.97,
        });

        tl.to(
          image,
          {
            opacity: 1,
            x: 0,
            scale: 1,
            duration: 1,
            ease: "power4.out",
          },
          0.3,
        );
      }

      if (line) {
        gsap.set(line, {
          scaleY: 0,
          transformOrigin: "top center",
        });

        tl.to(
          line,
          {
            scaleY: 1,
            duration: 1.2,
            ease: "power3.out",
          },
          0.35,
        );
      }

      gsap.set(navItems, {
        opacity: 0,
        y: 12,
      });

      tl.to(
        navItems,
        {
          opacity: 1,
          y: 0,
          duration: 0.5,
          stagger: 0.06,
          ease: "power3.out",
        },
        0.45,
      );
    }, section);

    return () => context.revert();
  }, []);

  useLayoutEffect(() => {
    const content = contentRef.current;
    const image = imageRef.current;

    if (!content || !image) return;

    const context = gsap.context(() => {
      const title = content.querySelector<HTMLElement>(".tnea-step-title");
      const description = content.querySelector<HTMLElement>(
        ".tnea-step-description",
      );
      const points = Array.from(
        content.querySelectorAll<HTMLElement>(".tnea-step-point"),
      );
      const imageElement = image.querySelector<HTMLElement>(".tnea-step-image");
      const stepNumber = content.querySelector<HTMLElement>(
        ".tnea-active-number",
      );

      gsap.set([title, description, ...points, stepNumber].filter(Boolean), {
        opacity: 0,
        y: 20,
      });

      if (imageElement) {
        gsap.set(imageElement, {
          opacity: 0,
          scale: 1.04,
        });
      }

      const tl = gsap.timeline();

      if (stepNumber) {
        tl.to(
          stepNumber,
          {
            opacity: 1,
            y: 0,
            duration: 0.45,
            ease: "power3.out",
          },
          0,
        );
      }

      if (title) {
        tl.to(
          title,
          {
            opacity: 1,
            y: 0,
            duration: 0.65,
            ease: "power4.out",
          },
          0.08,
        );
      }

      if (description) {
        tl.to(
          description,
          {
            opacity: 1,
            y: 0,
            duration: 0.55,
            ease: "power3.out",
          },
          0.18,
        );
      }

      if (points.length) {
        tl.to(
          points,
          {
            opacity: 1,
            y: 0,
            duration: 0.45,
            stagger: 0.055,
            ease: "power3.out",
          },
          0.25,
        );
      }

      if (imageElement) {
        tl.to(
          imageElement,
          {
            opacity: 1,
            scale: 1,
            duration: 0.9,
            ease: "power4.out",
          },
          0,
        );
      }
    });

    return () => context.revert();
  }, [activeIndex]);

  const handleStepChange = (index: number) => {
    if (index === activeIndex) return;

    setActiveIndex(index);
  };

  return (
    <section
      ref={sectionRef}
      className="overflow-hidden bg-gray-50 py-20 sm:py-24 lg:py-32"
    >
      <Container>
        {/* Header */}
        <div className="grid gap-4 lg:grid-cols-[1.2fr_1fr] lg:gap-8">
          <div>
            <p className="mb-4 text-sm uppercase tracking-[0.18em] text-primary-800/60">
              TNEA Step-by-Step
            </p>
            <SectionHeading as="h2">
              Your TNEA Journey Step by Step
            </SectionHeading>
          </div>

          <div className="flex items-end">
            <p
              ref={introRef}
              className="max-w-2xl text-base leading-relaxed text-gray-600 sm:text-lg"
            >
              Follow the TNEA application process from registration to reporting
              at the college. Select each stage to understand what happens at
              every step.
            </p>
          </div>
        </div>

        {/* Main Stepper */}
        <div className="mt-8 lg:mt-16">
          <div className="grid gap-12 grid-cols-1 lg:grid-cols-[250px_minmax(0,1fr)] lg:gap-6 xl:grid-cols-[320px_minmax(0,1fr)] xl:gap-8">
            {/* Step Navigation */}
            <div ref={navRef} className="relative">
              <div className="relative flex gap-4 justify-between overflow-x-auto pb-2 lg:block lg:overflow-hidden lg:pb-0">
                {/* Vertical progress line */}
                <div className="absolute left-[13px] top-5 hidden h-[calc(100%-40px)] w-px bg-primary-800/10 lg:block">
                  <div className="tnea-progress-line h-full w-full origin-top bg-primary-800/30" />
                </div>
                {steps.map((step, index) => {
                  const isActive = index === activeIndex;

                  return (
                    <button
                      key={step.number}
                      type="button"
                      onClick={() => handleStepChange(index)}
                      className={`tnea-nav-item cursor-pointer group relative flex shrink-0 items-center gap-4 text-left transition-all duration-300 lg:mb-5 lg:w-full ${
                        isActive
                          ? "text-primary-800"
                          : "text-gray-400 hover:text-primary-800"
                      }`}
                    >
                      {/* Number */}
                      <span
                        className={`relative z-10 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border text-[11px] ${
                          isActive
                            ? "border-accent-400 bg-accent-400 text-white"
                            : "border-gray-300 bg-gray-50 text-gray-400 group-hover:border-accent-400 group-hover:text-accent-400"
                        }`}
                      >
                        {step.number}
                      </span>

                      {/* Label */}
                      <span
                        className={`whitespace-nowrap font-semibold text-sm uppercase tracking-[0.12em] transition-all duration-300 lg:whitespace-normal ${
                          isActive
                            ? "translate-x-1 font-semibold text-accent-400"
                            : "group-hover:translate-x-1 group-hover:text-accent-400"
                        }`}
                      >
                        {step.navTitle}
                      </span>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Active Step Content */}
            <div ref={contentRef} className="min-w-0" key={activeStep.number}>
              <div className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr] xl:gap-10">
                {/* Text */}
                <div className="flex flex-col justify-center">
                  <div className="tnea-active-number mb-5 text-sm uppercase tracking-[0.18em] text-primary-800/50">
                    {activeStep.number} / {steps[steps.length - 1].number}
                  </div>

                  <SectionHeading as="h3">{activeStep.title}</SectionHeading>

                  <p className="tnea-step-description mt-6 max-w-xl text-gray-600">
                    {activeStep.description}
                  </p>

                  <div className="mt-8 space-y-4">
                    {activeStep.points.map((point, index) => (
                      <div
                        key={`${activeStep.number}-${index}`}
                        className="tnea-step-point flex items-start gap-3"
                      >
                        <span className="text-base mt-1.5 text-accent-400">
                          <FaCircleCheck />
                        </span>
                        <p className="text-sm leading-relaxed text-gray-700 sm:text-base">
                          {point}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Image */}
                <div
                  ref={imageRef}
                  className="relative overflow-hidden rounded-[2px] bg-gray-200"
                >
                  <div className="tnea-step-image relative aspect-4/3 lg:h-full w-full overflow-hidden">
                    <Image
                      src={activeStep.image}
                      alt={activeStep.title}
                      fill
                      sizes="(max-width: 1280px) 100vw, 50vw"
                      className="object-cover"
                    />

                    <div className="absolute inset-0 bg-gradient-to-t from-primary-800/30 via-transparent to-transparent" />

                    <div className="absolute bottom-5 left-5">
                      <span className="inline-flex bg-white/95 px-4 py-2 text-xs uppercase tracking-[0.14em] text-primary-800 backdrop-blur-sm">
                        TNEA Application
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Step controls */}
              <div className="mt-10 flex items-center justify-between border-t border-gray-200 pt-6">
                <button
                  type="button"
                  onClick={() => handleStepChange(Math.max(0, activeIndex - 1))}
                  disabled={activeIndex === 0}
                  className="group flex items-center gap-3 text-sm uppercase tracking-[0.12em] text-primary-800 transition-opacity disabled:pointer-events-none disabled:opacity-30 cursor-pointer"
                >
                  <span className="transition-transform duration-300 group-hover:-translate-x-1">
                    ←
                  </span>
                  Previous
                </button>

                <div className="hidden items-center gap-2 sm:flex">
                  {steps.map((step, index) => (
                    <button
                      key={step.number}
                      type="button"
                      aria-label={`Go to step ${step.number}`}
                      onClick={() => handleStepChange(index)}
                      className={`cursor-pointer h-1.5 rounded-full transition-all duration-300 ${
                        index === activeIndex
                          ? "w-8 bg-primary-800"
                          : "w-1.5 bg-gray-300 hover:bg-gray-500"
                      }`}
                    />
                  ))}
                </div>

                <button
                  type="button"
                  onClick={() =>
                    handleStepChange(
                      Math.min(steps.length - 1, activeIndex + 1),
                    )
                  }
                  disabled={activeIndex === steps.length - 1}
                  className="group flex items-center gap-3 text-sm uppercase tracking-[0.12em] text-primary-800 transition-opacity disabled:pointer-events-none disabled:opacity-30 cursor-pointer"
                >
                  Next
                  <span className="transition-transform duration-300 group-hover:translate-x-1">
                    →
                  </span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </Container>
    </section>
  );
}
